"""Adicionar tabela FaturaCartao para controle de pagamento por mes

Revision ID: 015e75f6d54f
Revises: 3e29eacb9659
Create Date: 2025-07-29 09:51:03.778882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015e75f6d54f'
down_revision = '3e29eacb9659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturas_cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('paga', sa.Boolean(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartoes_credito.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cartao_id', 'ano', 'mes', name='unique_fatura_mes')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faturas_cartao')
    # ### end Alembic commands ###
