"""Adiciona conta_pagamento_id aos cartoes de credito

Revision ID: 3d8f7559cd49
Revises: 895aae33aaa6
Create Date: 2025-07-28 21:42:38.733511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8f7559cd49'
down_revision = '895aae33aaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoes_credito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conta_pagamento_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contas', ['conta_pagamento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoes_credito', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conta_pagamento_id')

    # ### end Alembic commands ###
