"""Tornar conta_id nullable para cartoes de credito

Revision ID: 3e29eacb9659
Revises: 3d8f7559cd49
Create Date: 2025-07-28 22:26:27.532142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e29eacb9659'
down_revision = '3d8f7559cd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.alter_column('conta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.alter_column('conta_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
