"""Adiciona estrutura para transferencias

Revision ID: 3e4bd3ca2622
Revises: b5a06dad5404
Create Date: 2025-07-28 20:21:22.203916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4bd3ca2622'
down_revision = 'b5a06dad5404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferencia_grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transferencia_grupo_id', sa.Integer(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'transferencia_grupos', ['transferencia_grupo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('transferencia_grupo_id')

    op.drop_table('transferencia_grupos')
    # ### end Alembic commands ###
