"""Cria estrutura de categorias e subcategorias

Revision ID: 535aacd44020
Revises: a39b73f3d9a7
Create Date: 2025-07-28 11:01:13.590698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535aacd44020'
down_revision = 'a39b73f3d9a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('icone', sa.String(length=30), nullable=True))

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('lancamentos_categoria_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'subcategorias', ['subcategoria_id'], ['id'])
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lancamentos_categoria_id_fkey'), 'categorias', ['categoria_id'], ['id'])
        batch_op.drop_column('subcategoria_id')

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_column('icone')
        batch_op.drop_column('cor')

    op.drop_table('subcategorias')
    # ### end Alembic commands ###
