"""Adiciona estrutura de lancamentos e recorrencia

Revision ID: 566646208bd6
Revises: 535aacd44020
Create Date: 2025-07-28 16:47:18.734248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566646208bd6'
down_revision = '535aacd44020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao_base', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_vencimento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('data_pagamento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('recorrencia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'recorrencias', ['recorrencia_id'], ['id'])
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recorrencia_id')
        batch_op.drop_column('status')
        batch_op.drop_column('data_pagamento')
        batch_op.drop_column('data_vencimento')

    op.drop_table('recorrencias')
    # ### end Alembic commands ###
