"""Adiciona frequencia a recorrencias

Revision ID: 6cf7df5dc97b
Revises: 566646208bd6
Create Date: 2025-07-28 17:25:13.617579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf7df5dc97b'
down_revision = '566646208bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequencia', sa.String(length=20), server_default='Mensal', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.drop_column('frequencia')

    # ### end Alembic commands ###
