"""Adiciona tabela de cartoes de credito e coluna cartao_credito_id em lancamentos

Revision ID: 895aae33aaa6
Revises: 3e4bd3ca2622
Create Date: 2025-07-28 21:34:59.067969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895aae33aaa6'
down_revision = '3e4bd3ca2622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes_credito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('logo_imagem', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cartao_credito_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cartoes_credito', ['cartao_credito_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cartao_credito_id')

    op.drop_table('cartoes_credito')
    # ### end Alembic commands ###
