"""Adiciona campos detalhados à tabela Conta

Revision ID: a39b73f3d9a7
Revises: c6aa63800b9f
Create Date: 2025-07-28 09:35:02.672632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39b73f3d9a7'
down_revision = 'c6aa63800b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_conta', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('tipo_investimento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('saldo_inicial', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('logo_imagem', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.drop_column('logo_imagem')
        batch_op.drop_column('saldo_inicial')
        batch_op.drop_column('tipo_investimento')
        batch_op.drop_column('tipo_conta')

    # ### end Alembic commands ###
