"""Adiciona data de criacao aos lancamentos e recorrencias

Revision ID: b5a06dad5404
Revises: 6cf7df5dc97b
Create Date: 2025-07-28 19:19:14.704702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a06dad5404'
down_revision = '6cf7df5dc97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.Date(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.Date(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.drop_column('data_criacao')

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
