"""Altera colunas data_criacao para DateTime com timezone

Revision ID: c27d14e8afe9
Revises: 015e75f6d54f
Create Date: 2025-07-29 22:09:39.250065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27d14e8afe9'
down_revision = '015e75f6d54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartoes_credito', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('faturas_cartao', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('transferencia_grupos', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transferencia_grupos', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('recorrencias', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('faturas_cartao', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('cartoes_credito', schema=None) as batch_op:
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
